apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-pos-deployment
  labels:
    app: gateway-pos
    labels:
      app: gateway-pos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-pos
  template:
    metadata:
      labels:
        app: gateway-pos
    spec:
      containers:
        - name: gateway-pos
          image: ${ECR_IMAGE_URI}:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: gateway-pos-config
            - secretRef:
                name: gateway-pos-secrets